# Generated by Django 6.1 on 2026-08-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='academysession',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='academy.coursemodule'),
        ),
    ]
