# Generated by Django 6.1 on 2026-08-26 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_academysession_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalEvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.PositiveIntegerField(default=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'practical_evaluation_criteria',
            },
        ),
        migrations.RemoveField(
            model_name='practicalevaluation',
            name='rating',
        ),
        migrations.AddField(
            model_name='practicalevaluation',
            name='evaluated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicalevaluation',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practicalevaluation',
            name='max_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='practicalevaluation',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicalsession',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PracticalEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.PositiveIntegerField(default=0)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academy.practicalevaluationcriteria')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academy.practicalevaluation')),
            ],
            options={
                'db_table': 'practical_evaluation_scores',
                'unique_together': {('evaluation', 'criteria')},
            },
        ),
    ]
