# Generated by Django 6.1 on 2026-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_practicalevaluationcriteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='passing_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
