# Generated by Django 6.1 on 2026-08-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_assessment_passing_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='academy.batch'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('VERIFIED', 'Verified'), ('REVOKED', 'Revoked')], default='DRAFT', max_length=20),
        ),
    ]
