# Generated by Django 6.0.5 on 2026-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_remove_academyfee_academy_fee_amount_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyapplication',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
