# Generated by Django 6.0.5 on 2026-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_add_notes_to_academy_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyapplication',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='academyapplication',
            name='customer_response',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='academyapplication',
            name='customer_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academyapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_RESPONSE', 'Awaiting Customer Response'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
