from django.urls import path
from .views import (
    CourseListView,
    CourseDetailView,
    CourseModuleListView,
    BatchListView,
    BatchDetailView,
    AcademyApplicationCreateView,
    MyApplicationsView,
    CustomerRespondView,
    AdminNotifyApplicantView,
    MyEnrollmentsView,
    MyFeesView,
    MyAttendanceView,
    MyResultsView,
    MyCertificatesView,
    MyPracticalsView,
    AdminStudentListView,
    AdminStudentDetailView,
    AdminStudentEnrollView,
    AdminStudentRemoveView,
    AdminStudentUpdateView,
    PublicTrainerListView,
    PublicTrainerDetailView,
    AdminTrainerProfileView,
    AdminTrainerListView,
    AdminTrainerDetailView,
    AdminTrainerCreateView,
    AdminTrainerUpdateView,
    AdminTrainerDeactivateView,
    AdminTrainerBatchesView,
    AdminBatchListCreateView,
    AdminBatchDetailView,
    AdminBatchCancelView,
    AdminBatchCompleteView,
    AdminBatchReactivateView,
    AdminBatchStudentsView,
    TrainerBatchListView,
    StudentBatchAssessmentsView,
    StudentBatchAttendanceView,
    AdminCourseListView,
    AdminCourseDetailView,
    AdminCourseToggleStatusView,
    AdminCourseModuleListCreateView,
    AdminCourseModuleDetailView,
    AdminCourseCreateView,
    AdminCourseUpdateView,
    AdminSessionListView,
    AdminSessionDetailView,
    AdminSessionAttendanceView,
    AdminAssessmentListCreateView,
    AdminAssessmentDetailView,
    AdminAssessmentResultListCreateView,
    AdminAssessmentResultUpdateView,
    AdminPracticalSessionListCreateView,
    AdminPracticalEvaluationCreateUpdateView,
    AdminPracticalEvaluationCriteriaView,
    AdminPracticalSessionDetailView,
     AdminCertificateListView,
    AdminCertificateDetailView,
    AdminCertificateIssueView,
    AdminCertificateVerifyView,
    AdminCertificateRevokeView,
    AdminCertificateAutoGenerateView,
    AdminCertificateRestoreView,
    AdminCertificateCreateView,
    AdminCertificateUpdateView,
    AdminCertificateDeleteView,
    AdminAcademyFeeListView,
    AdminAcademyFeeMarkPaidView,
    AdminAcademyFeeUpdateView,
    AdminApplicationApproveView,
    AdminApplicationRejectView,

)

urlpatterns = [
    path("academy/courses/", CourseListView.as_view(), name="course_list"),
    path("academy/courses/<int:pk>/", CourseDetailView.as_view(), name="course_detail"),
    path("academy/courses/<int:course_id>/modules/", CourseModuleListView.as_view(), name="course_modules"),
    path("academy/batches/", BatchListView.as_view(), name="batch_list"),
    path("academy/batches/<int:pk>/", BatchDetailView.as_view(), name="batch_detail"),
    path("academy/apply/", AcademyApplicationCreateView.as_view(), name="apply"),
    path("academy/my-applications/", MyApplicationsView.as_view(), name="my_applications"),
    path("academy/applications/<int:pk>/respond/", CustomerRespondView.as_view(), name="application_respond"),
    path("admin/academy/applications/<int:pk>/notify/", AdminNotifyApplicantView.as_view(), name="application_notify"),
    path("academy/my-enrollments/", MyEnrollmentsView.as_view(), name="my_enrollments"),
    path("academy/my-fees/", MyFeesView.as_view(), name="my_fees"),
    path("academy/my-attendance/", MyAttendanceView.as_view(), name="my_attendance"),
    path("academy/my-results/", MyResultsView.as_view(), name="my_results"),
    path("academy/my-certificates/", MyCertificatesView.as_view(), name="my_certificates"),
    path("academy/my-practicals/", MyPracticalsView.as_view(), name="my_practicals"),
    path("admin/academy/courses/", AdminCourseListView.as_view(), name="admin_course_list"),
    path("admin/academy/courses/<int:pk>/", AdminCourseDetailView.as_view(), name="admin_course_detail"),
    path("admin/academy/courses/<int:pk>/toggle/", AdminCourseToggleStatusView.as_view(), name="admin_course_toggle"),
    path("admin/academy/courses/<int:course_id>/modules/", AdminCourseModuleListCreateView.as_view(), name="admin_course_modules"),
    path("admin/academy/courses/<int:course_id>/modules/<int:pk>/", AdminCourseModuleDetailView.as_view(), name="admin_course_module_detail"),
    path("admin/academy/courses/create/", AdminCourseCreateView.as_view(), name="admin_course_create"),
    path("admin/academy/courses/<int:pk>/update/", AdminCourseUpdateView.as_view(), name="admin_course_update"),
    path("admin/academy/batches/", AdminBatchListCreateView.as_view(), name="admin_batch_list_create"),
    path("admin/academy/batches/<pk>/", AdminBatchDetailView.as_view(), name="admin_batch_detail"),
    path("admin/academy/batches/<pk>/students/", AdminBatchStudentsView.as_view(), name="admin_batch_students"),
    path("admin/academy/batches/<pk>/cancel/", AdminBatchCancelView.as_view(), name="admin_batch_cancel"),
    path("admin/academy/batches/<pk>/complete/", AdminBatchCompleteView.as_view(), name="admin_batch_complete"),
    path("admin/academy/batches/<pk>/reactivate/", AdminBatchReactivateView.as_view(), name="admin_batch_reactivate"),
    path("admin/academy/batches/<batch_id>/sessions/", AdminSessionListView.as_view(), name="admin_batch_sessions"),
    path("admin/academy/batches/<int:batch_id>/students/<uuid:student_id>/attendance/", StudentBatchAttendanceView.as_view(), name="student_batch_attendance"),
    path("admin/academy/batches/<int:batch_id>/students/<uuid:student_id>/assessments/", StudentBatchAssessmentsView.as_view(), name="student_batch_assessments"),
    path("admin/academy/sessions/<pk>/", AdminSessionDetailView.as_view(), name="admin_session_detail"),
    path("admin/academy/sessions/<pk>/attendance/", AdminSessionAttendanceView.as_view(), name="admin_session_attendance"),
    path("admin/academy/students/", AdminStudentListView.as_view(), name="admin_student_list"),
    path("admin/academy/students/<pk>/", AdminStudentDetailView.as_view(), name="admin_student_detail"),
    path("admin/academy/students/<pk>/enroll/", AdminStudentEnrollView.as_view(), name="admin_student_enroll"),
    path("admin/academy/students/<pk>/remove/", AdminStudentRemoveView.as_view(), name="admin_student_remove"),
    path("admin/academy/students/<pk>/update/", AdminStudentUpdateView.as_view(), name="admin_student_update"),
    path("academy/trainers/", PublicTrainerListView.as_view(), name="public_trainer_list"),
    path("academy/trainers/<int:pk>/", PublicTrainerDetailView.as_view(), name="public_trainer_detail"),
    path("admin/academy/trainers/", AdminTrainerListView.as_view(), name="admin_trainer_list"),
    path("admin/academy/trainers/<str:pk>/profile/", AdminTrainerProfileView.as_view(), name="admin_trainer_profile"),
    path("admin/academy/trainers/create/", AdminTrainerCreateView.as_view(), name="admin_trainer_create"),
    path("admin/academy/trainers/<pk>/", AdminTrainerDetailView.as_view(), name="admin_trainer_detail"),
    path("admin/academy/trainers/<pk>/update/", AdminTrainerUpdateView.as_view(), name="admin_trainer_update"),
    path("admin/academy/trainers/<pk>/deactivate/", AdminTrainerDeactivateView.as_view(), name="admin_trainer_deactivate"),
    path("admin/academy/trainers/<pk>/batches/", AdminTrainerBatchesView.as_view(), name="admin_trainer_batches"),
    path("admin/academy/my-batches/", TrainerBatchListView.as_view(), name="trainer_batch_list"),
    path("admin/academy/assessments/", AdminAssessmentListCreateView.as_view(), name="admin_assessment_list_create"),
    path("admin/academy/assessments/<int:pk>/", AdminAssessmentDetailView.as_view(), name="admin_assessment_detail"),
    path("admin/academy/assessments/<int:assessment_id>/results/", AdminAssessmentResultListCreateView.as_view(), name="admin_assessment_results"),
    path("admin/academy/assessments/results/<int:pk>/", AdminAssessmentResultUpdateView.as_view(), name="admin_assessment_result_update"),
    path("admin/academy/practical/", AdminPracticalSessionListCreateView.as_view(), name="admin_practical_list_create"),
    path("admin/academy/practical/<int:pk>/", AdminPracticalSessionDetailView.as_view(), name="admin_practical_detail"),
    path("admin/academy/practical/<int:session_id>/evaluate/", AdminPracticalEvaluationCreateUpdateView.as_view(), name="admin_practical_evaluate"),
    path("admin/academy/practical/criteria/", AdminPracticalEvaluationCriteriaView.as_view(), name="admin_practical_criteria"),
    path('admin/academy/certificates/', AdminCertificateListView.as_view()),
    path('admin/academy/certificates/<int:pk>/', AdminCertificateDetailView.as_view()),
    path('admin/academy/certificates/<int:pk>/issue/', AdminCertificateIssueView.as_view()),
    path('admin/academy/certificates/<int:pk>/verify/', AdminCertificateVerifyView.as_view()),
    path('admin/academy/certificates/<int:pk>/revoke/', AdminCertificateRevokeView.as_view()),
    path('admin/academy/batches/<int:batch_id>/generate-certificates/', AdminCertificateAutoGenerateView.as_view()),
    path('admin/academy/certificates/<int:pk>/restore/', AdminCertificateRestoreView.as_view()),
    path('admin/academy/certificates/create/', AdminCertificateCreateView.as_view()),
    path('admin/academy/certificates/<int:pk>/update/', AdminCertificateUpdateView.as_view()),
    path('admin/academy/certificates/<int:pk>/delete/', AdminCertificateDeleteView.as_view()),
    path("admin/academy/fees/", AdminAcademyFeeListView.as_view(), name="admin_academy_fee_list"),
    path("admin/academy/fees/<pk>/", AdminAcademyFeeUpdateView.as_view(), name="admin_academy_fee_update"),
    path("admin/academy/fees/<pk>/mark-paid/", AdminAcademyFeeMarkPaidView.as_view(), name="admin_academy_fee_mark_paid"),
    path('admin/applications/<int:pk>/approve/',AdminApplicationApproveView.as_view(),name='admin-application-approve'),
    path('admin/applications/<int:pk>/reject/',AdminApplicationRejectView.as_view(),name='admin-application-reject'),

]