from django.urls import path
from .views import (
    ServiceListView,
    ServiceDetailView,
    CategoryListView,
    StaffListView,
    StaffDetailView,
    StaffServicesView,
    ServiceStaffView,
    StaffAvailabilityView,
    PackageListView,
    PackageDetailView,
    MyPackagesView,
    MyPackageUsageView,
    AppointmentListView,
    AppointmentDetailView,
    AppointmentCreateView,
    AppointmentCancelView,
    AppointmentRescheduleView,
    ReviewCreateView,
    MyReviewUpdateView,
    PublicReviewListView,
    AdminReviewListView,
    AdminReviewStatusView,
    CreateOrderView,
    VerifyPaymentView,
    PaymentCreateAPIView,
    PaymentDeleteAPIView
)

urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("services/", ServiceListView.as_view(), name="service_list"),
    path("services/<int:pk>/", ServiceDetailView.as_view(), name="service_detail"),
    path("services/<int:pk>/staff/", ServiceStaffView.as_view(), name="service_staff"),
    path("staff/", StaffListView.as_view(), name="staff_list"),
    path("staff/<int:pk>/", StaffDetailView.as_view(), name="staff_detail"),
    path("staff/<int:pk>/services/", StaffServicesView.as_view(), name="staff_services"),
    path("staff/<int:pk>/availability/", StaffAvailabilityView.as_view(), name="staff_availability"),
    path("packages/", PackageListView.as_view(), name="package_list"),
    path("packages/<int:pk>/", PackageDetailView.as_view(), name="package_detail"),
    path("my-packages/", MyPackagesView.as_view(), name="my_packages"),
    path("my-packages/<int:pk>/usage/", MyPackageUsageView.as_view(), name="my_package_usage"),
    path("appointments/", AppointmentListView.as_view(), name="appointment_list"),
    path("appointments/create/", AppointmentCreateView.as_view(), name="appointment_create"),
    path("appointments/<int:pk>/cancel/", AppointmentCancelView.as_view(), name="appointment_cancel"),
    path("appointments/<int:pk>/reschedule/", AppointmentRescheduleView.as_view(), name="appointment_reschedule"),
    path("appointments/<int:pk>/", AppointmentDetailView.as_view(), name="appointment_detail"),
    path("reviews/", ReviewCreateView.as_view(), name="review_create"),
    path("reviews/public/", PublicReviewListView.as_view(), name="review_public_list"),
    path("reviews/<int:pk>/", MyReviewUpdateView.as_view(), name="review_update"),
    path("admin/reviews/", AdminReviewListView.as_view(), name="admin_review_list"),
    path("admin/reviews/<int:pk>/status/", AdminReviewStatusView.as_view(), name="admin_review_status"),
    path("payments/create-order/", CreateOrderView.as_view(), name="create_order"),
    path("payments/verify/", VerifyPaymentView.as_view(), name="verify_payment"),
    path("payments/admin/create/", PaymentCreateAPIView.as_view(), name="admin_payment_create"),
    path("payments/admin/<int:pk>/delete/", PaymentDeleteAPIView.as_view(), name="admin_payment_delete"),
]