import client from './client';

export const academyApi = {
  getDashboard: () => client.get('/admin/academy/dashboard/'),
  getApplications: () => client.get('/admin/academy/applications/'),
  getApplicationById: (id) => client.get(`/admin/academy/applications/${id}/`),
  approveApplication: (id, data) => client.post(`/admin/academy/applications/${id}/approve/`, data),
  updateApplicationStatus: (id, data) => client.patch(`/admin/academy/applications/${id}/status/`, data),
  getCourses: () => client.get('/admin/academy/courses/'),
  getCourseById: (id) => client.get(`/admin/academy/courses/${id}/`),
  createCourse: (data) => {
    const isForm = typeof FormData !== 'undefined' && data instanceof FormData
    return client.post('/admin/academy/courses/create/', data, isForm
      ? { headers: { 'Content-Type': 'multipart/form-data' } }
      : undefined)
  },
  updateCourse: (id, data) => {
    const isForm = typeof FormData !== 'undefined' && data instanceof FormData
    return client.patch(`/admin/academy/courses/${id}/`, data, isForm
      ? { headers: { 'Content-Type': 'multipart/form-data' } }
      : undefined)
  },
  toggleCourseStatus: (id) => client.post(`/admin/academy/courses/${id}/toggle/`),
  getCourseModules: (courseId) => client.get(`/admin/academy/courses/${courseId}/modules/`),
  createCourseModule: (courseId, data) => client.post(`/admin/academy/courses/${courseId}/modules/`, data),
  updateCourseModule: (courseId, moduleId, data) => client.patch(`/admin/academy/courses/${courseId}/modules/${moduleId}/`, data),
  deleteCourseModule: (courseId, moduleId) => client.delete(`/admin/academy/courses/${courseId}/modules/${moduleId}/`),
  getBatches: () => client.get('/admin/academy/batches/'),
  getBatchById: (id) => client.get(`/admin/academy/batches/${id}/`),
  createBatch: (data) => client.post('/admin/academy/batches/', data),
  updateBatch: (id, data) => client.patch(`/admin/academy/batches/${id}/`, data),
  cancelBatch: (id) => client.post(`/admin/academy/batches/${id}/cancel/`),
  completeBatch: (id) => client.post(`/admin/academy/batches/${id}/complete/`),
  reactivateBatch: (id) => client.post(`/admin/academy/batches/${id}/reactivate/`),
  getBatchStudents: (id) => client.get(`/admin/academy/batches/${id}/students/`),
  getStudentBatchAttendance: (batchId, studentId) => client.get(`/admin/academy/batches/${batchId}/students/${studentId}/attendance/`),
  getStudentBatchAssessments: (batchId, studentId) => client.get(`/admin/academy/batches/${batchId}/students/${studentId}/assessments/`),
  getMyBatches: () => client.get('/admin/academy/my-batches/'),
  getBatchSessions: (batchId) => client.get(`/admin/academy/batches/${batchId}/sessions/`),
  createSession: (batchId, data) => client.post(`/admin/academy/batches/${batchId}/sessions/`, data),
  getSessionById: (id) => client.get(`/admin/academy/sessions/${id}/`),
  updateSession: (id, data) => client.patch(`/admin/academy/sessions/${id}/`, data),
  deleteSession: (id) => client.delete(`/admin/academy/sessions/${id}/`),
  getSessionAttendance: (sessionId) => client.get(`/admin/academy/sessions/${sessionId}/attendance/`),
  markAttendance: (sessionId, records) => client.post(`/admin/academy/sessions/${sessionId}/attendance/`, { records }),
  getStudents: (params) => client.get('/admin/academy/students/', { params }),
  getStudentById: (id) => client.get(`/admin/academy/students/${id}/`),
  enrollStudent: (id, data) => client.post(`/admin/academy/students/${id}/enroll/`, data),
  updateStudent: (id, data) => client.patch(`/admin/academy/students/${id}/update/`, data),
  removeStudent: (id) => client.post(`/admin/academy/students/${id}/remove/`),
  getTrainers: (params) => client.get('/admin/academy/trainers/', { params }),
  getTrainerById: (id) => client.get(`/admin/academy/trainers/${id}/`),
  createTrainer: (data) => client.post('/admin/academy/trainers/create/', data),
  updateTrainer: (id, data) => client.patch(`/admin/academy/trainers/${id}/update/`, data),
  deactivateTrainer: (id) => client.post(`/admin/academy/trainers/${id}/deactivate/`),
  getTrainerBatches: (id) => client.get(`/admin/academy/trainers/${id}/batches/`),
  getTrainerBatchesForAttendance: (trainerId) => client.get(`/admin/academy/trainers/${trainerId}/batches/`),
  getBatchStudentsAttendance: (batchId) => client.get(`/admin/academy/batches/${batchId}/students/`),
  getStudentAttendanceDetail: (batchId, studentId) =>
  client.get(`/admin/academy/batches/${batchId}/students/${studentId}/attendance/`),
  getAssessments: (params) => client.get('/admin/academy/assessments/', { params }),
  getAssessmentById: (id) => client.get(`/admin/academy/assessments/${id}/`),
  createAssessment: (data) => client.post('/admin/academy/assessments/', data),
  updateAssessment: (id, data) => client.patch(`/admin/academy/assessments/${id}/`, data),
  deleteAssessment: (id) => client.delete(`/admin/academy/assessments/${id}/`),
  getAssessmentResults: (assessmentId) => client.get(`/admin/academy/assessments/${assessmentId}/results/`),
  createAssessmentResult: (assessmentId, data) => client.post(`/admin/academy/assessments/${assessmentId}/results/`, data),
  updateAssessmentResult: (id, data) => client.patch(`/admin/academy/assessments/results/${id}/`, data),
  getPracticalSessions: (params) => client.get('/admin/academy/practical/', { params }),
  getPracticalSession: (id) => client.get(`/admin/academy/practical/${id}/`),
  createPracticalSession: (data) => client.post('/admin/academy/practical/', data),
  updatePracticalSession: (id, data) => client.patch(`/admin/academy/practical/${id}/`, data),
  deletePracticalSession: (id) => client.delete(`/admin/academy/practical/${id}/`),
  getPracticalCriteria: () => client.get('/admin/academy/practical/criteria/'),
  createEvaluation: (sessionId, data) => client.post(`/admin/academy/practical/${sessionId}/evaluate/`, data),
  updateEvaluation: (sessionId, data) => client.patch(`/admin/academy/practical/${sessionId}/evaluate/`, data),
  getCertificates: (params) => client.get('/admin/academy/certificates/', { params }),
  getCertificateById: (id) => client.get(`/admin/academy/certificates/${id}/`),
  issueCertificate: (id) => client.post(`/admin/academy/certificates/${id}/issue/`),
  verifyCertificate: (id) => client.post(`/admin/academy/certificates/${id}/verify/`),
  revokeCertificate: (id) => client.post(`/admin/academy/certificates/${id}/revoke/`),
  generateCertificates: (batchId) => client.post(`/admin/academy/batches/${batchId}/generate-certificates/`),
  restoreCertificate: (id) => client.post(`/admin/academy/certificates/${id}/restore/`),
  createCertificate: (data) => client.post('/admin/academy/certificates/create/', data),
  updateCertificate: (id, data) => client.patch(`/admin/academy/certificates/${id}/update/`, data),
  deleteCertificate: (id) => client.delete(`/admin/academy/certificates/${id}/delete/`),
  getPayments: (params) => client.get('/admin/payments/', { params }),
  getPaymentById: (id) => client.get(`/admin/payments/${id}/`),
  updatePaymentStatus: (id, data) => client.patch(`/admin/payments/${id}/update/`, data),
  getAcademyFees: (studentId) => client.get('/admin/academy/fees/', { params: { student_id: studentId } }),
  markFeePaid: (feeId) => client.post(`/admin/academy/fees/${feeId}/mark-paid/`),
};