from django.urls import path
from .views import (
    DashboardView,
    CustomerListView,
    StaffListView,
    RevenueReportView,
    AcademyDashboardView,
    ManageApplicationsView,
    ApproveApplicationView,
    ApplicationStatusUpdateView,
    AdminAppointmentListView,
    AdminAppointmentUpdateView,
    CustomerDetailView,
    CustomerCreateView,
    CustomerUpdateView,
    CustomerDeactivateView,
    AdminServiceCategoryDeactivateView,
    AdminServiceCategoryListView,
    AdminServiceDetailView,
    AdminServiceListView,
    AdminServiceCategoryDetailView,
    AdminServiceDeactivateView,
    AdminStaffListView,
    AdminStaffDetailView,
    AdminStaffDeactivateView,
    AdminStaffServiceListView,
    AdminStaffServiceDeleteView,
    AdminStaffAvailabilityView,
    AdminStaffAvailabilityDeleteView,
    AdminStaffLeaveApproveView,
    AdminStaffLeaveListView,
    UserAccountListView,
    UserAccountRoleUpdateView,
    AdminPackageListView,
    AdminPackageDetailView,
    AdminPackageDeactivateView,
    AdminPaymentListView,
    AdminPaymentDetailView,
    AdminPaymentUpdateView,
    AppointmentReportView,
    ServiceReportView,
    CustomerReportView,
    PackageReportView,
    ApplicationDetailView,
    AdminSalaryListView,
    AdminSalaryMarkPaidView,
    AdminSalaryDetailView,
    ContactInquiryCreateView,
    AdminContactInquiryListView,
    AdminContactInquiryDetailView,
    AdminContactInquiryReplyView,
)

urlpatterns = [
    path("admin/dashboard/", DashboardView.as_view(), name="dashboard"),
    path("admin/customers/", CustomerListView.as_view(), name="customers"),
    path("admin/customers/<uuid:pk>/", CustomerDetailView.as_view(), name="customer_detail"),
    path("admin/customers/create/", CustomerCreateView.as_view(), name="customer_create"),
    path("admin/customers/<uuid:pk>/update/", CustomerUpdateView.as_view(), name="customer_update"),
    path("admin/customers/<uuid:pk>/deactivate/", CustomerDeactivateView.as_view(), name="customer_deactivate"),
    path("admin/staff/", StaffListView.as_view(), name="staff_list"),
    path("admin/reports/revenue/", RevenueReportView.as_view(), name="revenue_report"),
    path("admin/academy/dashboard/", AcademyDashboardView.as_view(), name="academy_dashboard"),
    path("admin/academy/applications/", ManageApplicationsView.as_view(), name="applications"),
    path("admin/academy/applications/<int:pk>/status/", ApplicationStatusUpdateView.as_view(), name="application_status_update"),
    path("admin/academy/applications/<int:pk>/approve/", ApproveApplicationView.as_view(), name="approve_application"),
    path("admin/appointments/", AdminAppointmentListView.as_view(), name="admin_appointments"),
    path("admin/appointments/<int:pk>/", AdminAppointmentUpdateView.as_view(), name="admin_appointment_update"),
    path("admin/service-categories/", AdminServiceCategoryListView.as_view(), name="admin_service_category_list"),
    path("admin/service-categories/<int:pk>/", AdminServiceCategoryDetailView.as_view(), name="admin_service_category_detail"),
    path("admin/service-categories/<int:pk>/deactivate/", AdminServiceCategoryDeactivateView.as_view(), name="admin_service_category_deactivate"),
    path("admin/services/", AdminServiceListView.as_view(), name="admin_service_list"),
    path("admin/services/<int:pk>/", AdminServiceDetailView.as_view(), name="admin_service_detail"),
    path("admin/services/<int:pk>/deactivate/", AdminServiceDeactivateView.as_view(), name="admin_service_deactivate"),
    path("admin/staff-directory/", AdminStaffListView.as_view(), name="admin_staff_list"),
    path("admin/staff-directory/<int:pk>/", AdminStaffDetailView.as_view(), name="admin_staff_detail"),
    path("admin/staff-directory/<int:pk>/deactivate/", AdminStaffDeactivateView.as_view(), name="admin_staff_deactivate"),
    path("admin/staff-directory/<int:staff_id>/services/", AdminStaffServiceListView.as_view(), name="admin_staff_services"),
    path("admin/staff-services/<int:pk>/", AdminStaffServiceDeleteView.as_view(), name="admin_staff_service_delete"),
    path("admin/staff-directory/<int:staff_id>/availability/", AdminStaffAvailabilityView.as_view(), name="admin_staff_availability"),
    path("admin/staff-availability/<int:pk>/", AdminStaffAvailabilityDeleteView.as_view(), name="admin_staff_availability_delete"),
    path("admin/staff-directory/<int:staff_id>/leaves/", AdminStaffLeaveListView.as_view(), name="admin_staff_leaves"),
    path("admin/staff-leaves/<int:pk>/approve/", AdminStaffLeaveApproveView.as_view(), name="admin_staff_leave_approve"),
    path("admin/users/", UserAccountListView.as_view(), name="admin_user_list"),
    path("admin/users/<uuid:pk>/role/", UserAccountRoleUpdateView.as_view(), name="admin_user_role_update"),
    path("admin/packages/", AdminPackageListView.as_view(), name="admin-package-list"),
    path("admin/packages/<int:pk>/", AdminPackageDetailView.as_view(), name="admin-package-detail"),
    path("admin/packages/<int:pk>/deactivate/", AdminPackageDeactivateView.as_view(), name="admin-package-deactivate"),
    path("admin/payments/", AdminPaymentListView.as_view(), name="admin_payments"),
    path("admin/payments/<int:pk>/", AdminPaymentDetailView.as_view(), name="admin_payment_detail"),
    path("admin/payments/<int:pk>/update/", AdminPaymentUpdateView.as_view(), name="admin_payment_update"),
    path("admin/reports/revenue/", RevenueReportView.as_view(), name="revenue_report"),
    path("admin/reports/appointments/", AppointmentReportView.as_view(), name="appointment_report"),
    path("admin/reports/customers/", CustomerReportView.as_view(), name="customer_report"),
    path("admin/reports/services/", ServiceReportView.as_view(), name="service_report"),
    path("admin/reports/packages/", PackageReportView.as_view(), name="package_report"),
    path("admin/academy/applications/<int:pk>/", ApplicationDetailView.as_view(), name="application_detail"),
    path("admin/salaries/", AdminSalaryListView.as_view(), name="admin_salary_list"),
    path("admin/salaries/<int:pk>/mark-paid/", AdminSalaryMarkPaidView.as_view(), name="admin_salary_mark_paid"),
    path("admin/salaries/<int:pk>/", AdminSalaryDetailView.as_view(), name="admin_salary_detail"),
    # Contact inquiries
    path("contact/", ContactInquiryCreateView.as_view(), name="contact_create"),
    path("admin/contact-inquiries/", AdminContactInquiryListView.as_view(), name="admin_contact_list"),
    path("admin/contact-inquiries/<int:pk>/", AdminContactInquiryDetailView.as_view(), name="admin_contact_detail"),
    path("admin/contact-inquiries/<int:pk>/reply/", AdminContactInquiryReplyView.as_view(), name="admin_contact_reply"),
]