# Generated by Django 6.1 on 2026-08-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='salon.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.staff')),
            ],
            options={
                'db_table': 'staff_services',
                'ordering': ['-created_at'],
                'unique_together': {('staff', 'service')},
            },
        ),
    ]
