# Generated by Django 6.1 on 2026-08-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_staffavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('PERSONAL', 'Personal Leave'), ('VACATION', 'Vacation'), ('OTHER', 'Other')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='salon.staff')),
            ],
            options={
                'db_table': 'staff_leaves',
                'ordering': ['-start_date'],
            },
        ),
    ]
