# Generated by Django 6.1 on 2026-08-20 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_staffleave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_type', models.CharField(choices=[('CLASSIC', 'Classic'), ('PREMIUM', 'Premium'), ('EXCLUSIVE', 'Exclusive')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_days', models.PositiveIntegerField(help_text='Package valid for how many days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('USED', 'Fully Used')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.package')),
            ],
            options={
                'db_table': 'customer_packages',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PackageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('customer_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='salon.customerpackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service')),
            ],
            options={
                'db_table': 'package_usage',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='How many times this service is included')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='salon.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service')),
            ],
            options={
                'db_table': 'package_benefits',
                'unique_together': {('package', 'service')},
            },
        ),
    ]
