# Generated by Django 6.1 on 2026-08-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_payment_invoice_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
