# Generated by Django 6.1 on 2026-09-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payments', to='salon.package'),
        ),
    ]
