# Generated by Django 6.1 on 2026-09-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_remove_academyfee_academy_fee_amount_positive_and_more'),
        ('salon', '0012_payment_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='academy_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='academy.academyfee'),
        ),
        migrations.AddField(
            model_name='refund',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='salon.appointment'),
        ),
    ]
