# Generated by Django 6.1 on 2026-09-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_remove_refund_academy_fee_remove_refund_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image_before',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
