# Generated by Django 6.1 on 2026-09-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0016_add_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CONFIRMATION', 'Confirmation'), ('REMINDER_24H', '24h Reminder'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='salon.appointment')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
